### ISSUE TITLE
rsync is parametrized with --ignore-existing

### ISSUE THREAD

**Issue by Gabriel-Espinoza** [APHONlC/Linux-Tamriel-Trade-Center#2]
I just downloaded the script from ESOUI and realized my files did not update even though the script said it updated it. So I added `-v` to `rsync` in order to get a detailed information in the operation.

To my surprise, all files were skipped because the files already existed in the destination directory.

To fix this, I removed the `--ignore-existing` parameter in `rsync`, just then files were replaced.

My final command was like follows:
```bash
rsync -v -auvzhPX --progress ~/Downloads/PriceTable/. "/home/$USER/SteamLibrary/steamapps/compatdata/306130/pfx/drive_c/users/steamuser/My Documents/Elder Scrolls Online/live/AddOns/TamrielTradeCentre/"
```

**Comment by ronlaws86** [comment]
I came here to report the same issue. adding --ignore-existing is the improper command argument for this use case as it means files with the same name will not be sent, urgo, no pricetable update :) 

Simply removing this flag from the rsync line fixes the problem and the proce table gets updates correctly.

**Comment by ronlaws86** [comment]
Line 65
```diff
-rsync -auvzhPX --ignore-existing --progress ~/Downloads/PriceTable/. "/home/$USER/PortWINE/PortProton/drive_c/users/steamuser/My Documents/Elder Scrolls Online/live/AddOns/TamrielTradeCentre/"
+rsync -auvzhPX --ignore-existing --progress ~/Downloads/PriceTable/. "/home/$USER/PortWINE/PortProton/drive_c/users/steamuser/My Documents/Elder Scrolls Online/live/AddOns/TamrielTradeCentre/"
```

**Comment by lg-eim** [comment]
Came here to report rsync not working. Probably should have looked at existing bugs before fixing it on my own. I ended up just replacing it with:

yes | cp -R ~/Downloads/PriceTable/*.lua "/home/$USER/.steam/steam/steamapps/compatdata/306130/pfx/drive_c/users/steamuser/My Documents/Elder Scrolls Online/live/AddOns/TamrielTradeCentre/"

Also a lot of the high intensity background colors are unreadable in Manjaro's default colors scheme for Konsole so I changed some of those with this handy reference https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux.

**Comment by APHONlC** [comment]
Thanks for the reports, it seems that I forgot to remove those lines while I was testing the script.
I've updated 3 of the scripts since they are the ones affected upon checking and only this [Release](https://github.com/APHONlC/Linux-Tamriel-Trade-Center/releases/tag/O-LINUX-STEAM-RAW) have the working code and will not need an update.
